### ISSUE TITLE
Fire as She Bears - Sleek Hull not Giving dex bonus

### ISSUE THREAD

**Issue by Barhidous** [shadowchemosh/HL-Pack-Pathfinder#113]
According to the pdf, a sleek hull is -4 str + 4 dex, but right now it is only giving -4 str.

**Comment by shadowchemosh** [comment]
My PDF says "Str –4, +1 maneuverability rating". 

Is there a new PDF out? I got mine from the kickstarter and dont think I have access to any errata.

**Comment by Barhidous** [comment]
[image: Inline image 1]

Is what mine says, pretty sure it's the most up to date.

**Comment by Barhidous** [comment]
Dexterity (Dex) = 10 + the number of Rigging 
Locations – the number of Hull Locations. A ship’s 
Dexterity will be further modified by whether you opted 
to build with Sleek (+4) or Broad (–4) Hulls
![5-29-2017 11-17-46 am](https://cloud.githubusercontent.com/assets/29033133/26559241/41033f32-4463-11e7-92a4-37f0bf1f3563.jpg)

**Comment by shadowchemosh** [comment]
Oh wow good catch. Will get that fixed. 

On the flip side I wish they didn't spread the info out so much in the book.
