### ISSUE TITLE
Path of War: missing Harbinger Disciplines

### ISSUE THREAD

**Issue by shaver** [shadowchemosh/HL-Pack-Pathfinder#115]
I don't see any Iron Tortoise or Eternal Guardian disciplines in the latest Pathfinder Pack. Reading http://forums.wolflair.com/showthread.php?t=47690 leads me to believe that they were present in the Path of War source, but I can't find a link to that directly, so I figured they'd be in the Pathfinder Pack. Are they elsewhere?

I have both "DSP - Path of War" and "DSP - Path of War Expanded Playtest" selected.

Thanks for your help!

E: I'm using Pathfinder Pack 1.8, and Hero Lab 8.1

**Comment by shadowchemosh** [comment]
Something does look strange here....  I will take a closer look once I am home tonight...

**Comment by shadowchemosh** [comment]
For Harbinger class I have the latest Expanded PoW book.  It says

> A harbinger begins her career with knowledge of five martial maneuvers. The disciplines available to her are Cursed Razor, Riven Hourglass, Scarlet Throne, Shattered Mirror, and Veiled Moon.

Harbinger does not get Iron Tortoise or Eternal Guardian disciplines.  Version 1.8 of the Pack updated the allowed disciplines of all PoW classes to the latest printing of the books.

When I switch to a Warder class that does get Iron Tortoise I see a whole bunch to choose from......

**Comment by shaver** [comment]
My apologies, you're totally correct. I was working from a guide that
listed the others for some reason.

How embarrassing!

**Comment by shadowchemosh** [comment]
No problem.  Better safe to report something then never reporting an issue. =)
