### ISSUE TITLE
Ultimate Psionics - Soulknife Additional Configuration

### ISSUE THREAD

**Issue by Volgrath** [shadowchemosh/HL-Pack-Pathfinder#123]
Would it be possible to enable a drop-down list as has been implemented for Emulate Melee Weapon for the Blade Skill: Additional Configuration?

**Comment by shadowchemosh** [comment]
Just posting to say I did see this and seems like it should be possible.  But I have not yet had time to look into the exact details yet.  Will let you know as soon as I can.

Thanks!
