### ISSUE TITLE
PoW:Ex error in Eldritch Energy Hammer short text

### ISSUE THREAD

**Issue by phlidwsn** [shadowchemosh/HL-Pack-Pathfinder#149]
Short Desc for Eldritch Energy Hammer lists damage as 10d6 active energy + dispel magic.

Actual is dispel magic + 1d6 force per dispelled spell level

**Comment by phlidwsn** [comment]
Just put in a pull req with the fixed text for this.(#150 )

**Comment by shadowchemosh** [comment]
The PR was merged... closing out this issue... Thanks!!! =)
