### ISSUE TITLE
Ultimate Psionics - Aberrant Aegis 'transformed' not activating Customizations

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-Pathfinder#15]
_From @phlidwsn on November 21, 2015 4:45_

Aberrant Aegis when the 'transformed' state is checked has the following issues:
Does not apply the DR from the base Aegis.
Does not apply the enhancement bonus to STR from Brawn.  This also applies to Dex from Nimble and CON from Hardy.  Evasion likewise does not appear when transformed if that customization is selected.

_Copied from original issue: shadowchemosh/HL-Pack-3PP#75_

**Comment by KeltecRFB** [comment]
I have also observed this bug.

~Aka Anderlorn
