### ISSUE TITLE
Ultimate Psionics - Tactician Power Missing

### ISSUE THREAD

**Issue by shadowchemosh** [shadowchemosh/HL-Pack-Pathfinder#2]
_From @shadowchemosh on October 3, 2015 20:29_

http://forums.wolflair.com/showthread.php?t=53984

Shift the Tide (Tactician 4) appears to be missing entirely.

_Copied from original issue: shadowchemosh/HL-Pack-3PP#71_

**Comment by psych777** [comment]
not sure when was added but shift the tide exists now
