### ISSUE TITLE
Knowlege Martail and Knowledge Psionics wont show up under skill menu

### ISSUE THREAD

**Issue by NightmarePaladin** [shadowchemosh/HL-Pack-Pathfinder#48]
Knowlege Martail and Knowledge Psionics wont show up under skill menu same with Auto-Hypnosis

**Comment by shadowchemosh** [comment]
Yeah. Was reported on the boards thanks.  The issue is related to being "Unique" and being bootstrapped to the Consolidated skills.  I am not sure how to fix yet...
