### ISSUE TITLE
Greater Unarmed Strike

### ISSUE THREAD

**Issue by NightmarePaladin** [shadowchemosh/HL-Pack-Pathfinder#49]
Greater Unarmed Strike's progression is off it jumps from 1d8 to 2d6 instead of 1d8 to 1d10

**Comment by shadowchemosh** [comment]
I think this is actually a Lone Wolf bug.  I noticed this behavior for the Katana also but was so tired I couldn't remember with the latest Official Errata what 1d8 changes to.

I say LW issue because the script is using Helper.DamageUp and the code logic is all written and maintained by LW.

**Comment by shadowchemosh** [comment]
I have reported this to LW.  Lets see what they say.  Hmm need to locate that official errata on dice size increases...

**Comment by shadowchemosh** [comment]
So I found that HL is increasing the damage size correctly based on the Errata document on damage dice:
http://paizo.com/paizo/faq/v5748nruor1fm#v5748eaic9t3f

So the issue becomes what is correct now the feat? Or Paizo's errata?

**Comment by shadowchemosh** [comment]
I found how the Monk damage is done and I am going to mimic that logic....
