### ISSUE TITLE
Daish Expertise

### ISSUE THREAD

**Issue by NightmarePaladin** [shadowchemosh/HL-Pack-Pathfinder#52]
Daisho Expertise still uses Lone Wolfs Damage Die Step which  #causes Incorrect damage.

**Comment by shadowchemosh** [comment]
This feat says "**Increase the damage die of katanas and wakizashi you wield by one die step.**"  The feat is increasing the die size by "one" step as per the Paizo Errata on Dice Sizes.  So the 1d8 Katana should be correctly going to 2d6 damage.

The feat does not list "dice" sizes it says use the one die step.  Meaning we default to the global rule of how Pathfinder works.

Unless you mean something else I don't see any issue to fix.
