### ISSUE TITLE
Ultimate Psionics: Forgeborn Aegis FCB should be +1/4

### ISSUE THREAD

**Issue by phlidwsn** [shadowchemosh/HL-Pack-Pathfinder#90]
Ultimate Psionics: Forgeborn Aegis FCB should be +1/4 customization point, not +1.

Also, does not appear to actually add the customization point when chosen.

**Comment by shadowchemosh** [comment]
I fixed the fact that it should be 1/4 not 1.  It looks like the +1 point was going into the "Reconfigure" class ability.  Will need to check the book to see what makes sense for where the point is suppose to go.

Doing fixes for all the different Forgeborn FCB's as lots of little issues in them all.  Sigh....

**Comment by shadowchemosh** [comment]
This FCB should be adding to the Astral Suite customization point total.  I have this fixed.
