### ISSUE TITLE
Ultimate Psionics - Psychic Warrior Path Powers coiunting against powers known

### ISSUE THREAD

**Issue by phlidwsn** [shadowchemosh/HL-Pack-Pathfinder#93]
Currently Path Powers are counting towards the Powers Known for a Psychic Warrior.  Page 54 of UPsi, under Warrior's Path, indicates that "Powers gained from a path do not count against the number of powers known"

Reproduce: Take a blank level 3 psywar, add feral warrior path, click on 'special abilities' and set the two path powers.  Despite having selected 0 powers known, it now shows 2/3 powers known.

**Comment by shadowchemosh** [comment]
This is a bug introduced with the last LW update.  LW made fixes/changes to the way Psionic Powers work and now bootstrapped powers are counting towards powers known.

Will have to try and figure out how to stop this.  Thanks!

**Comment by shadowchemosh** [comment]
Well none of the 'standard' way spells would be fixed is working.  I am getting no response from LW on how to fix.  I will have to use a brute force/hack fix to force the values to be correct.  Not the way I prefer but it should work.
